#ifndef APPLICATION_H
#define APPLICATION_H


#endif // APPLICATION_H
#define VIEW_SCALE_UP 1

#define GLOBAL_SCREEN_FIXED_WIDTH 600*VIEW_SCALE_UP
#define GLOBAL_SCREEN_FIXED_HEIGHT 800*VIEW_SCALE_UP



#define HOME_PAGE_MODULE 0
#define BOOK_SHELF_MODULE 1


//==================HomePage Module===========================
#define HPM_LEFTBOOK_RECT 0
#define HPM_RIGHTBOOK_RECT 1
#define HPM_LEFTBOOK_NAME_RECT 2
#define HPM_RIGHTBOOK_NAME_RECT 3
#define HPM_LEFTBOOK_AUTHOR_RECT 4
#define HPM_RIGHTBOOK_AUTHOR_RECT 5
#define HPM_NEW_BOOK 6
#define HPM_LASTPAGE_BUTTON 7
#define HPM_FIRSTBOOK_RECT 8
#define HPM_SECONDBOOK_RECT 9
#define HPM_THIRDBOOK_RECT 10
#define HPM_NEXTPAGE_BUTTON 11
#define HPM_FIRSTBOOK_NAME 12
#define HPM_SECONDBOOK_NAME 13
#define HPM_THIRDBOOK_NAME 14
#define HPM_BOOKSHELF_BUTTON 15
#define HPM_APP_BUTTON 16
#define HPM_SETTING_BUTTON 17
#define HPM_BOOKSHELF_NAME 18
#define HPM_APP_NAME 19
#define HPM_SETTING_NAME 20




//====================Bookshelf module==========================
#define BSM_SEARCH_BUTTON 30
#define BSM_HOME_BUTTON 31
#define BSM_TEXT 29
#define BSM_READ_ORDER_ITEM 32
#define BSM_READ_BOOK_NAME 33
#define BSM_READ_TIME 34
#define BSM_READ_BOOK_AUTHOR 35
#define BSM_FIRST_BOOK 36
#define BSM_SECOND_BOOK_37
#define BSM_THIRD_BOOK 38
#define BSM_FOURTH_BOOK 39
#define BSM_FIVTH_BOOK 40
#define BSM_SIXTH_BOOK 41
#define BSM_SEVENTH_BOOK 42
#define BSM_EIGHTTH_BOOK 43
#define BSM_NINTH_BOOK 44
#define BSM_FIRST_PAGE 45
#define BSM_LAST_PAGE 46
#define BSM_PAGES_CONTENT 47
#define BSM_NEXT_PAEG 48
#define BSM_END_PAGE 49









